export const FETCH_START = 'fetchStart'
export const FETCH_END = 'fetchEnd'
export const SET_ARTICLE = 'setArticle'
export const SET_TAG = 'setTag'
export const SET_COMMENT = 'setComment'
export const SET_LOGIN_IN = 'setLoginIn'
export const SET_lOGIN_OUT = 'setLoginOut'
